### PR TITLE
MODEUR-49: MainVerticleTest, Tenant2ApiTest, ApiIT ordering

### PR DESCRIPTION
**Pull request by adamdickmeiss**
After ApiIT was added it was no longer possible to run Tenant2ApiTest
and MainVerticleTest without failures in IntelliJ Idea. For details see
https://issues.folio.org/browse/MODEUR-49

Solution: reset RestAssured static initializers.
I don't know why ApiIT was an integration test
to be begin with. After this change, it no longer need to be.
So it could be renamed as well.

### CODE REVIEW

**Comment by julianladisch** [comment]
I cannot reproduce your issue.

mod-eusage-reports has two plugins:
* maven-surefire-plugin
* maven-failsafe-plugin

The [maven-surefire-plugin runs during this maven phase](https://maven.apache.org/surefire/maven-surefire-plugin/index.html):
* test

The [maven-failsafe-plugin runs during these maven phases](https://maven.apache.org/surefire/maven-failsafe-plugin/index.html):
* pre-integration-test (for setting up the integration test environment)
* integration-test (for running the integration tests)
* post-integration-test (for tearing down the integration test environment)
* verify (for checking the results of the integration tests)

The [maven-surefire-plugin by default executes these files](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html):
* "**/Test*.java" - includes all of its subdirectories and all Java filenames that start with "Test".
* "**/*Test.java" - includes all of its subdirectories and all Java filenames that end with "Test".
* "**/*Tests.java" - includes all of its subdirectories and all Java filenames that end with "Tests".
* "**/*TestCase.java" - includes all of its subdirectories and all Java filenames that end with "TestCase".

The [maven-failsafe-plugin by default executes these files](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html):
* "**/IT*.java" - includes all of its subdirectories and all Java filenames that start with "IT".
* "**/*IT.java" - includes all of its subdirectories and all Java filenames that end with "IT".
* "**/*ITCase.java" - includes all of its subdirectories and all Java filenames that end with "ITCase".

The test phase of maven-surefire-plugin runs before the phases of maven-failsave-plugin, and they run a different set of test classes.
Please provide a reproducer where ApiIT can influcence MainVerticleTest or Tenant2ApiTest.

**Comment by adamdickmeiss** [comment]
> I cannot reproduce your issue.
> 
> mod-eusage-reports has two plugins:
> 
> * maven-surefire-plugin
> * maven-failsafe-plugin
> 
> The [maven-surefire-plugin runs during this maven phase](https://maven.apache.org/surefire/maven-surefire-plugin/index.html):
> 
> * test
> 
> The [maven-failsafe-plugin runs during these maven phases](https://maven.apache.org/surefire/maven-failsafe-plugin/index.html):
> 
> * pre-integration-test (for setting up the integration test environment)
> * integration-test (for running the integration tests)
> * post-integration-test (for tearing down the integration test environment)
> * verify (for checking the results of the integration tests)
> 
> The [maven-surefire-plugin by default executes these files](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html):
> 
> * "**/Test*.java" - includes all of its subdirectories and all Java filenames that start with "Test".
> * "**/*Test.java" - includes all of its subdirectories and all Java filenames that end with "Test".
> * "**/*Tests.java" - includes all of its subdirectories and all Java filenames that end with "Tests".
> * "**/*TestCase.java" - includes all of its subdirectories and all Java filenames that end with "TestCase".
> 
> The [maven-failsafe-plugin by default executes these files](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html):
> 
> * "**/IT*.java" - includes all of its subdirectories and all Java filenames that start with "IT".
> * "**/*IT.java" - includes all of its subdirectories and all Java filenames that end with "IT".
> * "**/*ITCase.java" - includes all of its subdirectories and all Java filenames that end with "ITCase".
> 
> The test phase of maven-surefire-plugin runs before the phases of maven-failsave-plugin, and they run a different set of test classes.
> Please provide a reproducer where ApiIT can influcence MainVerticleTest or Tenant2ApiTest.

I can't make a reproducer from maven! But it will fail if the ApiIT is not an integration test. Why is it an integration test?? To fix this issue? Not a good reason.

The annoying issue for me is that I can not run tests in Idea editor anymore. Do I need another excuse to get this fixed?

**Comment by julianladisch** [comment]
> why ApiIT was an integration test to be begin with?

Does the [ApiIT javadoc](https://github.com/folio-org/mod-eusage-reports/blob/master/src/test/java/org/folio/tlib/api/ApiIT.java#L34) answer you question?

> Tests that shaded jar and Dockerfile work.

In the maven `test` phase there is no shaded jar and therefore this test can only run in the maven `integration-test` phase.

**Comment by julianladisch** [comment]
You should have mentioned that this is a workaround needed only for IntelliJ Idea. I've extended the pull request description.

**Review by julianladisch — APPROVED** [review]

**Comment by adamdickmeiss** [comment]
> You should have mentioned that this is a workaround needed only for IntelliJ Idea. I've extended the pull request description.

Thank you!

**Pull request merged**
