### PR TITLE
APPDESCRIP-28: update erm-usage/files interface id to be valid for Eureka platform

### PR DESCRIPTION
**Pull request by yaroslav-kiriak**
[APPDESCRIP-28](https://folio-org.atlassian.net/browse/APPDESCRIP-28)

Related PR: https://github.com/folio-org/app-erm-usage/pull/1

Purpose: update erm-usage/files interface id to be valid for Eureka platform

### CODE REVIEW

**Review by pfilippov-epam — APPROVED** [review]

**Review by mykolam-epm — APPROVED** [review]

**Review by MikeTaylor — CHANGES_REQUESTED** [review]
This is breaking change since the module now requires an interface that it didn't require before. I assume that whatever module previously provided the `erm-usage/files` interface has also had a breaking change applied so the name of what it provides now matches what this module expects to consume. Are we 100% confident that we have updated all modules that are affected by this change? Do we really want to make new major releases of all of them?

I think we ought to at least consider instead changing Eureka so that it's OK with interface names that contain slashes.

**Comment by OleksiiKuzminov** [comment]
@MikeTaylor Thank you for your review. We have reviewed all the places where this interface is being used. It is not an easy change and I guess it is better to align the interface names with FOLIO guidelines.

https://dev.folio.org/guidelines/naming-conventions/

The major version will be released.

**Review by alb3rtino — CHANGES_REQUESTED** [review]
Please increase modules major version.
https://github.com/folio-org/mod-eusage-reports/blob/master/pom.xml#L5

**Review by alb3rtino — APPROVED** [review]

**Comment by alb3rtino** [comment]
@MikeTaylor Are you ok with this?

**Comment by MikeTaylor** [comment]
> @MikeTaylor Are you ok with this?

I'm really not. Changing the name of an interface is a big deal that not only means all old consumers will stop working, but also means that new consumers won't work with the old provider. Fixing that involved a cascade of new major releases that all have to be done simultaneously.

It's a huge amount of work to achieve so very little, and I don't think we should be wasting our time on such things. Just leave the poor interface name alone, close https://folio-org.atlassian.net/browse/APPDESCRIP-28 as WONTDO, and let's all move on to more productive work. The only rational reason I can see to proceed with this set of PRs is to improve our GitHub commit stats.

If you are still not persuaded by my argument, let's bring in the FOLIO TC for some more perspectives.

**Comment by craigmcnally** [comment]
> > @MikeTaylor Are you ok with this?
> 
> I'm really not. Changing the name of an interface is a big deal that not only means all old consumers will stop working, but also means that new consumers won't work with the old provider. Fixing that involved a cascade of new major releases that all have to be done simultaneously.
> 
> It's a huge amount of work to achieve so very little, and I don't think we should be wasting our time on such things. Just leave the poor interface name alone, close https://folio-org.atlassian.net/browse/APPDESCRIP-28 as WONTDO, and let's all move on to more productive work. The only rational reason I can see to proceed with this set of PRs is to improve our GitHub commit stats.
> 
> If you are still not persuaded by my argument, let's bring in the FOLIO TC for some more perspectives.

I wanted to clarify that this does present a problem for the Eureka platform.  There Kong routes are annotated (via tags) with the name of the interface which provides the endpoint.  My understanding is that these characters are not supported in the tags.  So, there are practical implications here, we're not just doing this for the sake of ensuring everyone is following guidelines.

**Comment by craigmcnally** [comment]
> schema violation (tags.4: invalid tag 'erm-usage/files': expected printable ascii (except `,` and `/`) or valid utf-8 sequences)

**Comment by MikeTaylor** [comment]
Thanks, @craigmcnally, that does change the equation somewhat. It's a very strange requirement for Kong to impose, but I suppose that's the nature of using third-party software.

In the Eureka architecture, do sys-admin scripts post directly to Kong, or is there a thin layer in between that acts as a FOLIO-aware façade? If the latter, could we have this layer transliterate slashes to underscores in interface names?

**Comment by craigmcnally** [comment]
> Thanks, @craigmcnally, that does change the equation somewhat. It's a very strange requirement for Kong to impose, but I suppose that's the nature of using third-party software.
> 
> In the Eureka architecture, do sys-admin scripts post directly to Kong, or is there a thin layer in between that acts as a FOLIO-aware façade? If the latter, could we have this layer transliterate slashes to underscores in interface names?

The mgr-* services create/manage the kong services and routes.  In theory something like that is possible, but why not just adhere to the naming guidelines which have been around for years?  Doing that transliteration does add complexity which is avoidable, and could get confusing.  Say you're troubleshooting something and want to lookup the route in Kong.  If you search by the name in the module descriptor you won't find anything.  You need to know about these rules/mappings/transliterations and apply them yourself.

**Comment by MikeTaylor** [comment]
@craigmcnally I do see both sides of this. But "_just_ adhere to the naming guidelines" entails a lot of busywork which IMHO is better avoided. (Including a major release of one of my own modules.)

On the other hand, I see from https://folio-snapshot.dev.folio.org/settings/developer/okapi-console?tab=interfaces that `erm-usage/files` seems to be the only extant interface containing a slash. So the upheaval is not quite as great as it could have been.

Let's give it another 24 hours. If no-one else chips in on my side of this argument, I will withdraw gracefully.

**Comment by craigmcnally** [comment]
> @craigmcnally I do see both sides of this. But "_just_ adhere to the naming guidelines" entails a lot of busywork which IMHO is better avoided. (Including a major release of one of my own modules.)
> 
> On the other hand, I see from https://folio-snapshot.dev.folio.org/settings/developer/okapi-console?tab=interfaces that `erm-usage/files` seems to be the only extant interface containing a slash. So the upheaval is not quite as great as it could have been.
> 
> Let's give it another 24 hours. If no-one else chips in on my side of this argument, I will withdraw gracefully.

@MikeTaylor please approve so we can merge this.  Thank you

**Comment by MikeTaylor** [comment]
Thank you for your patience. In the absence of anyone else weighing in, I graciously concede defeat on this one :-)

**Review by MikeTaylor — APPROVED** [review]

**Pull request merged**
