### PR TITLE
csv=true makes report return text/csv MODEUR-60

### PR DESCRIPTION
**Pull request by adamdickmeiss**

### CODE REVIEW

**Comment by skoczko** [comment]
I mentioned this before: this makes no sense to me, conceptually. With this change we will need to change the interface again when we address MODEUR-54 MODEUR-53 and MODEUR-50 as the CSV format will diverge from JSON and will no longer contain the same data.

**Comment by adamdickmeiss** [comment]
> I mentioned this before: this makes no sense to me, conceptually. With this change we will need to change the interface again when we address MODEUR-54 MODEUR-53 and MODEUR-50 as the CSV format will diverge from JSON and will no longer contain the same data.

No. The CSV format is schema less at the moment. If we decide that this service changes its JSON response, then we change the JSON response. JSON !=  CSV.

**Comment by skoczko** [comment]
@adamdickmeiss I expanded on why I think this is a bad idea on MODEUR-60. But I don't want this issues to hold Mike's work hostage so I'll approve -- let's move on.

**Review by skoczko — APPROVED** [review]

**Review by julianladisch — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
